project_name: psychic_eureka
before:
  hooks:
    - go mod download
builds:
  - id: psychic-eureka
    dir: ./cmd/psychic-eureka
    binary: psychic-eureka
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - dockerfile: build/package/Dockerfile
    image_templates:
      - "ctrombley/psychic-eureka:{{ .Tag }}"
      - "ctrombley/psychic-eureka:v{{ .Major }}.{{ .Minor }}"
      - "ctrombley/psychic-eureka:latest"
    ids:
      - psychic-eureka
